# Generated by Django 2.2 on 2019-12-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
