# Generated by Django 2.2 on 2019-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191213_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_icon',
            field=models.ImageField(height_field=30, upload_to='images/', width_field=30),
        ),
    ]
