# Generated by Django 2.2 on 2019-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191213_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
